### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Ionutiobag",
  "email": "kafka@example.com",
  "address": "123 Main St, Springfield, USA22",
  "dateOfBirth": "1990-01-01",
  "registeredDate": "2023-10-01"
}

###