### Creates a new patient entity
POST http://lb-0ca90514.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Ionutiule",
  "email": "kafka12@example.com",
  "address": "123 Main St, Springfield, USA22",
  "dateOfBirth": "1990-01-01",
  "registeredDate": "2023-10-01"
}

###