### Update an existing patient
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "John Doe UPDATED",
  "email": "wowow@example.com",
  "address": "123 Main St, Springfield, USA",
  "dateOfBirth": "1990-01-01"
}

###